/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMaintenanceOfflineSweepRouteImport } from './routes/api/public/maintenance/offline-sweep'
import { Route as ApiPublicBinsBinIdTelemetryRouteImport } from './routes/api/public/bins/$binId/telemetry'
import { Route as ApiPublicVehiclesVehicleIdCollectRouteImport } from './routes/api/public/vehicles/$vehicleId/collect'
import { Route as ApiPublicVehiclesVehicleIdLocationRouteImport } from './routes/api/public/vehicles/$vehicleId/location'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceOfflineSweepRoute =
  ApiPublicMaintenanceOfflineSweepRouteImport.update({
    id: '/api/public/maintenance/offline-sweep',
    path: '/api/public/maintenance/offline-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBinsBinIdTelemetryRoute =
  ApiPublicBinsBinIdTelemetryRouteImport.update({
    id: '/api/public/bins/$binId/telemetry',
    path: '/api/public/bins/$binId/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVehiclesVehicleIdCollectRoute =
  ApiPublicVehiclesVehicleIdCollectRouteImport.update({
    id: '/api/public/vehicles/$vehicleId/collect',
    path: '/api/public/vehicles/$vehicleId/collect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVehiclesVehicleIdLocationRoute =
  ApiPublicVehiclesVehicleIdLocationRouteImport.update({
    id: '/api/public/vehicles/$vehicleId/location',
    path: '/api/public/vehicles/$vehicleId/location',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/maintenance/offline-sweep': typeof ApiPublicMaintenanceOfflineSweepRoute
  '/api/public/bins/$binId/telemetry': typeof ApiPublicBinsBinIdTelemetryRoute
  '/api/public/vehicles/$vehicleId/collect': typeof ApiPublicVehiclesVehicleIdCollectRoute
  '/api/public/vehicles/$vehicleId/location': typeof ApiPublicVehiclesVehicleIdLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/maintenance/offline-sweep': typeof ApiPublicMaintenanceOfflineSweepRoute
  '/api/public/bins/$binId/telemetry': typeof ApiPublicBinsBinIdTelemetryRoute
  '/api/public/vehicles/$vehicleId/collect': typeof ApiPublicVehiclesVehicleIdCollectRoute
  '/api/public/vehicles/$vehicleId/location': typeof ApiPublicVehiclesVehicleIdLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/maintenance/offline-sweep': typeof ApiPublicMaintenanceOfflineSweepRoute
  '/api/public/bins/$binId/telemetry': typeof ApiPublicBinsBinIdTelemetryRoute
  '/api/public/vehicles/$vehicleId/collect': typeof ApiPublicVehiclesVehicleIdCollectRoute
  '/api/public/vehicles/$vehicleId/location': typeof ApiPublicVehiclesVehicleIdLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/maintenance/offline-sweep'
    | '/api/public/bins/$binId/telemetry'
    | '/api/public/vehicles/$vehicleId/collect'
    | '/api/public/vehicles/$vehicleId/location'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/maintenance/offline-sweep'
    | '/api/public/bins/$binId/telemetry'
    | '/api/public/vehicles/$vehicleId/collect'
    | '/api/public/vehicles/$vehicleId/location'
  id:
    | '__root__'
    | '/'
    | '/api/public/maintenance/offline-sweep'
    | '/api/public/bins/$binId/telemetry'
    | '/api/public/vehicles/$vehicleId/collect'
    | '/api/public/vehicles/$vehicleId/location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicMaintenanceOfflineSweepRoute: typeof ApiPublicMaintenanceOfflineSweepRoute
  ApiPublicBinsBinIdTelemetryRoute: typeof ApiPublicBinsBinIdTelemetryRoute
  ApiPublicVehiclesVehicleIdCollectRoute: typeof ApiPublicVehiclesVehicleIdCollectRoute
  ApiPublicVehiclesVehicleIdLocationRoute: typeof ApiPublicVehiclesVehicleIdLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance/offline-sweep': {
      id: '/api/public/maintenance/offline-sweep'
      path: '/api/public/maintenance/offline-sweep'
      fullPath: '/api/public/maintenance/offline-sweep'
      preLoaderRoute: typeof ApiPublicMaintenanceOfflineSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bins/$binId/telemetry': {
      id: '/api/public/bins/$binId/telemetry'
      path: '/api/public/bins/$binId/telemetry'
      fullPath: '/api/public/bins/$binId/telemetry'
      preLoaderRoute: typeof ApiPublicBinsBinIdTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vehicles/$vehicleId/collect': {
      id: '/api/public/vehicles/$vehicleId/collect'
      path: '/api/public/vehicles/$vehicleId/collect'
      fullPath: '/api/public/vehicles/$vehicleId/collect'
      preLoaderRoute: typeof ApiPublicVehiclesVehicleIdCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vehicles/$vehicleId/location': {
      id: '/api/public/vehicles/$vehicleId/location'
      path: '/api/public/vehicles/$vehicleId/location'
      fullPath: '/api/public/vehicles/$vehicleId/location'
      preLoaderRoute: typeof ApiPublicVehiclesVehicleIdLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicMaintenanceOfflineSweepRoute: ApiPublicMaintenanceOfflineSweepRoute,
  ApiPublicBinsBinIdTelemetryRoute: ApiPublicBinsBinIdTelemetryRoute,
  ApiPublicVehiclesVehicleIdCollectRoute:
    ApiPublicVehiclesVehicleIdCollectRoute,
  ApiPublicVehiclesVehicleIdLocationRoute:
    ApiPublicVehiclesVehicleIdLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
